baseURL = "https://prezaei.de/"
title = "Pejman Rezaei"
theme = "PaperMod"

[params]
  author = "Pejman Rezaei"
  ShowCodeCopyButtons = true
  ShowReadingTime = false
  ShowPostNavLinks = true

[params.list]
  showSummary = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 4
